version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/draft-content-suggestions
    docker:
      - image: golang:1
        environment:
          GOPATH: /go
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
    steps:
      - checkout
      - run:
          name: External dependencies
          command: |
            go get -u github.com/mattn/goveralls
            go get -u github.com/jstemmer/go-junit-report
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Make result folders
          command: |
            mkdir -p ${CIRCLE_TEST_REPORTS}
            mkdir -p ${CIRCLE_COVERAGE_REPORT}
      - run:
          name: Download vendored dependancies
          command: dep ensure -v -vendor-only
      - run:
          name: Go build
          command: go build -v
      - run:
          name: Run Tests
          command: |
            go test -race -cover -coverprofile=$CIRCLE_COVERAGE_REPORT/coverage.out ./... | go-junit-report > $CIRCLE_TEST_REPORTS/junit.xml
      - run:
          name: Upload coverage
          command: goveralls -coverprofile=${CIRCLE_COVERAGE_REPORT}/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-results
  dockerfile:
    working_directory: /draft-content-suggestions
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
  dredd:
    working_directory: /go/src/github.com/Financial-Times/draft-content-suggestions
    docker:
      - image: bankrs/golang-dredd:go1.10.0-dredd5.1.5
        environment:
          GOPATH: /go
          API_YML: /go/src/github.com/Financial-Times/draft-content-suggestions/_ft/api.yml
          SUGGESTIONS_ENDPOINT: http://localhost:9000/content/suggest
          SUGGESTIONS_GTG_ENDPOINT: http://localhost:9000/content/suggest/__gtg
          DRAFT_CONTENT_ENDPOINT: http://localhost:9000/drafts/content
          DRAFT_CONTENT_GTG_ENDPOINT: http://localhost:9000/__gtg
          SUGGESTIONS_API_KEY: 12345
      - image: peteclarkft/ersatz:stable
    steps:
      - checkout
      - run:
          name: External Dependencies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Download vendored dependancies
          command: dep ensure -v -vendor-only
      - run:
          name: Go Build
          command: go build -v
      - run:
          name: Dredd API Testing
          command: dredd
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dredd
      - dockerfile:
          requires:
            - build
