# Default values for draft-content-suggestions.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"

eksCluster: false

replicaCount: 2
image:
  repository: coco/draft-content-suggestions
  version: "" # should be set explicitly at installation
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 64Mi
  limits:
    memory: 256Mi
env:
  ENV_VAR_1: "default value"
